/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    products: Product;
    distributors: Distributor;
    'wizard-crop-categories': WizardCropCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    'wizard-crop-categories': WizardCropCategoriesSelect<false> | WizardCropCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('el' | 'en') | ('el' | 'en')[];
  globals: {
    'nav-copy': NavCopy;
    'home-copy': HomeCopy;
    'about-copy': AboutCopy;
    'products-copy': ProductsCopy;
    'distributors-copy': DistributorsCopy;
    'contact-copy': ContactCopy;
    'animal-feed-copy': AnimalFeedCopy;
    'cookies-copy': CookiesCopy;
  };
  globalsSelect: {
    'nav-copy': NavCopySelect<false> | NavCopySelect<true>;
    'home-copy': HomeCopySelect<false> | HomeCopySelect<true>;
    'about-copy': AboutCopySelect<false> | AboutCopySelect<true>;
    'products-copy': ProductsCopySelect<false> | ProductsCopySelect<true>;
    'distributors-copy': DistributorsCopySelect<false> | DistributorsCopySelect<true>;
    'contact-copy': ContactCopySelect<false> | ContactCopySelect<true>;
    'animal-feed-copy': AnimalFeedCopySelect<false> | AnimalFeedCopySelect<true>;
    'cookies-copy': CookiesCopySelect<false> | CookiesCopySelect<true>;
  };
  locale: 'el' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  description?: string | null;
  /**
   * URL-friendly identifier (e.g. "microorganism-products"). Do not change after creation.
   */
  slug: string;
  /**
   * Lucide icon name (e.g. "FlaskConical", "Sprout", "Droplets").
   */
  icon?: string | null;
  /**
   * Display order (lower = first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description?: string | null;
  /**
   * URL-friendly identifier (e.g. "sublic"). Do not change after creation.
   */
  slug: string;
  category: number | ProductCategory;
  image?: (number | null) | Media;
  isBio?: boolean | null;
  /**
   * Display order within category (lower = first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: number;
  /**
   * URL-friendly identifier (e.g. "attica-sterea-evia"). Do not change after creation.
   */
  slug: string;
  region: string;
  areas?: string | null;
  /**
   * Greek administrative regions this distributor covers (used to highlight the map).
   */
  regionIds: (
    | 'east-macedonia-thrace'
    | 'central-macedonia'
    | 'west-macedonia'
    | 'epirus'
    | 'thessaly'
    | 'ionian-islands'
    | 'west-greece'
    | 'central-greece'
    | 'attica'
    | 'peloponnese'
    | 'north-aegean'
    | 'south-aegean'
    | 'crete'
  )[];
  /**
   * Optional company name if different from the distributor contact.
   */
  company?: string | null;
  contacts?:
    | {
        name: string;
        phone?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Map pin latitude (e.g. 37.9838).
   */
  latitude: number;
  /**
   * Map pin longitude (e.g. 23.7275).
   */
  longitude: number;
  /**
   * Display order (lower = first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Controls the Product Finder wizard on the homepage — categories, crops within each, and recommended products per growth phase.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wizard-crop-categories".
 */
export interface WizardCropCategory {
  id: number;
  /**
   * URL-friendly identifier (e.g. "vegetables"). Do not change after creation.
   */
  slug: string;
  name: string;
  description?: string | null;
  /**
   * e.g. 🥦
   */
  emoji: string;
  /**
   * Filename under /public/images/crops/ (e.g. "vegetables.jpg").
   */
  image?: string | null;
  /**
   * Tailwind gradient classes (e.g. "from-green-500 to-emerald-600").
   */
  color?: string | null;
  /**
   * Display order on the wizard (lower = first).
   */
  order?: number | null;
  /**
   * Individual crops shown when "agronomist" flow picks this category.
   */
  crops?:
    | {
        /**
         * Identifier (e.g. "tomato").
         */
        slug: string;
        name: string;
        emoji: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Growth phases shown after a user picks a crop, with recommended products per phase.
   */
  phases?:
    | {
        /**
         * Identifier (e.g. "flowering").
         */
        slug: string;
        name: string;
        description?: string | null;
        emoji: string;
        /**
         * Products recommended for this phase. Pick from the Products collection.
         */
        products?: (number | Product)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'distributors';
        value: number | Distributor;
      } | null)
    | ({
        relationTo: 'wizard-crop-categories';
        value: number | WizardCropCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  category?: T;
  image?: T;
  isBio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  slug?: T;
  region?: T;
  areas?: T;
  regionIds?: T;
  company?: T;
  contacts?:
    | T
    | {
        name?: T;
        phone?: T;
        role?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wizard-crop-categories_select".
 */
export interface WizardCropCategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  emoji?: T;
  image?: T;
  color?: T;
  order?: T;
  crops?:
    | T
    | {
        slug?: T;
        name?: T;
        emoji?: T;
        id?: T;
      };
  phases?:
    | T
    | {
        slug?: T;
        name?: T;
        description?: T;
        emoji?: T;
        products?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Top-nav labels, footer headings, and shared UI strings used across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-copy".
 */
export interface NavCopy {
  id: number;
  common?: {
    home?: string | null;
    products?: string | null;
    about?: string | null;
    distributors?: string | null;
    animalFeed?: string | null;
    contact?: string | null;
    privacyPolicy?: string | null;
    viewAll?: string | null;
    learnMore?: string | null;
    callUs?: string | null;
    emailUs?: string | null;
    followUs?: string | null;
    allRightsReserved?: string | null;
  };
  header?: {
    ourProducts?: string | null;
    viewAllProducts?: string | null;
  };
  footer?: {
    description?: string | null;
    products?: string | null;
    company?: string | null;
    aboutUs?: string | null;
    partners?: string | null;
    followUs?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content that appears on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-copy".
 */
export interface HomeCopy {
  id: number;
  hero?: {
    title?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
    viewProducts?: string | null;
    yearsInGreece?: string | null;
    partnerFarmers?: string | null;
    greeceCoverage?: string | null;
  };
  mission?: {
    title?: string | null;
    description1?: string | null;
    highlight1?: string | null;
    description2?: string | null;
    description3?: string | null;
    highlight2?: string | null;
    description4?: string | null;
    resultsTitle?: string | null;
    result1?: string | null;
    result2?: string | null;
    result3?: string | null;
    futureVision?: string | null;
    sustainableFuture?: string | null;
    futureVisionEnd?: string | null;
  };
  stats?: {
    title?: string | null;
    years?: string | null;
    farmers?: string | null;
    regions?: string | null;
    products?: string | null;
  };
  showcase?: {
    title?: string | null;
    subtitle?: string | null;
    tagline?: string | null;
    showcase1?: string | null;
    showcase2?: string | null;
    showcase3?: string | null;
    showcase4?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content on the /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-copy".
 */
export interface AboutCopy {
  id: number;
  about?: {
    title?: string | null;
    subtitle?: string | null;
    ourStory?: string | null;
    storyP1?: string | null;
    storyP2?: string | null;
    storyP3?: string | null;
    microsporeTitle?: string | null;
    microsporeP1?: string | null;
    microsporeP2?: string | null;
    ourMission?: string | null;
    missionP1?: string | null;
    missionP2?: string | null;
    missionP3?: string | null;
    rdTitle?: string | null;
    rdP1?: string | null;
    rdP2?: string | null;
    ourCommitment?: string | null;
    commitmentP1?: string | null;
    commitmentP2?: string | null;
    ourValues?: string | null;
    valuesSubtitle?: string | null;
    responsibility?: string | null;
    responsibilityDesc?: string | null;
    integrity?: string | null;
    integrityDesc?: string | null;
    sustainability?: string | null;
    sustainabilityDesc?: string | null;
    innovation?: string | null;
    innovationDesc?: string | null;
    ourJourney?: string | null;
    journeySubtitle?: string | null;
    founding?: string | null;
    foundingDesc?: string | null;
    expansion?: string | null;
    expansionDesc?: string | null;
    innovationMilestone?: string | null;
    innovationMilestoneDesc?: string | null;
    growth?: string | null;
    growthDesc?: string | null;
    rebranding?: string | null;
    rebrandingDesc?: string | null;
    today?: string | null;
    todayDesc?: string | null;
    regionsCoverage?: string | null;
    biotechProducts?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the /products listing and category pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-copy".
 */
export interface ProductsCopy {
  id: number;
  products?: {
    title?: string | null;
    subtitle?: string | null;
    viewCategory?: string | null;
    viewProduct?: string | null;
    allProducts?: string | null;
    categories?: string | null;
    notFoundTitle?: string | null;
    notFoundDesc?: string | null;
    contactUs?: string | null;
    ourCategories?: string | null;
    categoriesDesc?: string | null;
    viewAllProducts?: string | null;
    backToProducts?: string | null;
    productCatalog?: string | null;
    catalogComingSoon?: string | null;
    requestPriceList?: string | null;
    call?: string | null;
    otherCategories?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the /distributors page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors-copy".
 */
export interface DistributorsCopy {
  id: number;
  distributors?: {
    title?: string | null;
    subtitle?: string | null;
    findDistributor?: string | null;
    region?: string | null;
    phone?: string | null;
    mapTitle?: string | null;
    contact?: string | null;
    callComerco?: string | null;
    selectRegion?: string | null;
    selectRegionDesc?: string | null;
    allPartners?: string | null;
    teamCoversGreece?: string | null;
    notFoundTitle?: string | null;
    notFoundDesc?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the /contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-copy".
 */
export interface ContactCopy {
  id: number;
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    businessHours?: string | null;
    weekdays?: string | null;
    weekends?: string | null;
    ourLocation?: string | null;
    openInMaps?: string | null;
    followUs?: string | null;
    followUsDesc?: string | null;
    needHelp?: string | null;
    needHelpDesc?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the /animal-feed page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-feed-copy".
 */
export interface AnimalFeedCopy {
  id: number;
  animalFeed?: {
    title?: string | null;
    subtitle?: string | null;
    downloadCatalogue?: string | null;
    ourProducts?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Cookie consent banner and settings dialog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-copy".
 */
export interface CookiesCopy {
  id: number;
  cookies?: {
    title?: string | null;
    description?: string | null;
    readPrivacy?: string | null;
    forMoreInfo?: string | null;
    acceptAll?: string | null;
    acceptNecessary?: string | null;
    settings?: string | null;
    cookieSettings?: string | null;
    necessaryCookies?: string | null;
    necessaryDesc?: string | null;
    analyticsCookies?: string | null;
    analyticsDesc?: string | null;
    marketingCookies?: string | null;
    marketingDesc?: string | null;
    savePreferences?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-copy_select".
 */
export interface NavCopySelect<T extends boolean = true> {
  common?:
    | T
    | {
        home?: T;
        products?: T;
        about?: T;
        distributors?: T;
        animalFeed?: T;
        contact?: T;
        privacyPolicy?: T;
        viewAll?: T;
        learnMore?: T;
        callUs?: T;
        emailUs?: T;
        followUs?: T;
        allRightsReserved?: T;
      };
  header?:
    | T
    | {
        ourProducts?: T;
        viewAllProducts?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        products?: T;
        company?: T;
        aboutUs?: T;
        partners?: T;
        followUs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-copy_select".
 */
export interface HomeCopySelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        description?: T;
        viewProducts?: T;
        yearsInGreece?: T;
        partnerFarmers?: T;
        greeceCoverage?: T;
      };
  mission?:
    | T
    | {
        title?: T;
        description1?: T;
        highlight1?: T;
        description2?: T;
        description3?: T;
        highlight2?: T;
        description4?: T;
        resultsTitle?: T;
        result1?: T;
        result2?: T;
        result3?: T;
        futureVision?: T;
        sustainableFuture?: T;
        futureVisionEnd?: T;
      };
  stats?:
    | T
    | {
        title?: T;
        years?: T;
        farmers?: T;
        regions?: T;
        products?: T;
      };
  showcase?:
    | T
    | {
        title?: T;
        subtitle?: T;
        tagline?: T;
        showcase1?: T;
        showcase2?: T;
        showcase3?: T;
        showcase4?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-copy_select".
 */
export interface AboutCopySelect<T extends boolean = true> {
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ourStory?: T;
        storyP1?: T;
        storyP2?: T;
        storyP3?: T;
        microsporeTitle?: T;
        microsporeP1?: T;
        microsporeP2?: T;
        ourMission?: T;
        missionP1?: T;
        missionP2?: T;
        missionP3?: T;
        rdTitle?: T;
        rdP1?: T;
        rdP2?: T;
        ourCommitment?: T;
        commitmentP1?: T;
        commitmentP2?: T;
        ourValues?: T;
        valuesSubtitle?: T;
        responsibility?: T;
        responsibilityDesc?: T;
        integrity?: T;
        integrityDesc?: T;
        sustainability?: T;
        sustainabilityDesc?: T;
        innovation?: T;
        innovationDesc?: T;
        ourJourney?: T;
        journeySubtitle?: T;
        founding?: T;
        foundingDesc?: T;
        expansion?: T;
        expansionDesc?: T;
        innovationMilestone?: T;
        innovationMilestoneDesc?: T;
        growth?: T;
        growthDesc?: T;
        rebranding?: T;
        rebrandingDesc?: T;
        today?: T;
        todayDesc?: T;
        regionsCoverage?: T;
        biotechProducts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-copy_select".
 */
export interface ProductsCopySelect<T extends boolean = true> {
  products?:
    | T
    | {
        title?: T;
        subtitle?: T;
        viewCategory?: T;
        viewProduct?: T;
        allProducts?: T;
        categories?: T;
        notFoundTitle?: T;
        notFoundDesc?: T;
        contactUs?: T;
        ourCategories?: T;
        categoriesDesc?: T;
        viewAllProducts?: T;
        backToProducts?: T;
        productCatalog?: T;
        catalogComingSoon?: T;
        requestPriceList?: T;
        call?: T;
        otherCategories?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors-copy_select".
 */
export interface DistributorsCopySelect<T extends boolean = true> {
  distributors?:
    | T
    | {
        title?: T;
        subtitle?: T;
        findDistributor?: T;
        region?: T;
        phone?: T;
        mapTitle?: T;
        contact?: T;
        callComerco?: T;
        selectRegion?: T;
        selectRegionDesc?: T;
        allPartners?: T;
        teamCoversGreece?: T;
        notFoundTitle?: T;
        notFoundDesc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-copy_select".
 */
export interface ContactCopySelect<T extends boolean = true> {
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        phone?: T;
        email?: T;
        address?: T;
        businessHours?: T;
        weekdays?: T;
        weekends?: T;
        ourLocation?: T;
        openInMaps?: T;
        followUs?: T;
        followUsDesc?: T;
        needHelp?: T;
        needHelpDesc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-feed-copy_select".
 */
export interface AnimalFeedCopySelect<T extends boolean = true> {
  animalFeed?:
    | T
    | {
        title?: T;
        subtitle?: T;
        downloadCatalogue?: T;
        ourProducts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-copy_select".
 */
export interface CookiesCopySelect<T extends boolean = true> {
  cookies?:
    | T
    | {
        title?: T;
        description?: T;
        readPrivacy?: T;
        forMoreInfo?: T;
        acceptAll?: T;
        acceptNecessary?: T;
        settings?: T;
        cookieSettings?: T;
        necessaryCookies?: T;
        necessaryDesc?: T;
        analyticsCookies?: T;
        analyticsDesc?: T;
        marketingCookies?: T;
        marketingDesc?: T;
        savePreferences?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}